### ISSUE TITLE
没有找到resources_zh_CN.jar这个包啊？

### ISSUE THREAD

**Issue by Eddie-he** [ewen0930/PyCharm-Chinese#1]
没有找到resources_zh_CN.jar这个包啊？

**Comment by hotea** [comment]
1. clone 代码
2. cd 进代码目录
3. bash package.cmd  ( 若找不到jar命令，则需要安装配置 java）
4. 将生成的中文jar拷贝到相应lib目录，sudo cp resources_zh.jar /usr/lib/pycharm-community/lib

**Comment by adminlinzi** [comment]
@Eddie-he  楼主，这汉化效果咋样。给力吗

**Comment by carbont** [comment]
为这个还得装个java么。。。。还是算了。

**Comment by adminlinzi** [comment]
@carbont  https://github.com/adminlinzi/mygitworks/blob/master/resources_zhCN.jar  下载这个，现成的。另外，感谢原作者分享

**Comment by ewen0930** [comment]
上Github，大家都不开[release]吗？

**Comment by simple2source** [comment]
支持2016.3专业版的吗？

**Comment by ewen0930** [comment]
@simple2source 更新了2016.3专业版的，欢迎小白鼠

**Comment by simple2source** [comment]
小白鼠初体验，macos 专业版可用，不过里面的部分还没翻译的。在用用一段时间试试。
放到 /Applications/PyCharm.app/Contents/lib/ 即可

**Comment by torchcode** [comment]
你们都是用的linux或者mac系统吗？没有人用win7的？  win7是不是放在、JetBrains\PyCharm 2016.3.1\lib  下面啊？

**Comment by ewen0930** [comment]
@torchcode 对的，放在安装目录的 /lib/ 里即可！

**Comment by ghost** [comment]
windows下 cmd换行符有问题，脚本运行不了

**Comment by ewen0930** [comment]
我也用的 windows，没发现问题；是不是你没有java环境？

**Comment by WangYves** [comment]
2017.3，win10，按照说明放到lib下,重启Pycharm还是英文界面，压缩包里边的文件夹是libs，这个有影响吗？

**Comment by ewen0930** [comment]
以前是 libs，后来改 lib 了，说明还没变更过来！

**Comment by sunnnnnnnny** [comment]
@adminlinzi  你好，https://github.com/adminlinzi/mygitworks/blob/master/resources_zhCN.jar  这个打不开了，能否分享一下？谢谢

**Comment by carbont** [comment]
我记得这文件不用打开，不是压缩包，直接放到pycharm的哪个位置就可以了。不在家，没有电脑用。以上发自我的iPhone------------------ 原始邮件 ------------------发件人: 18810319795  <notifications@github.com>发送时间: 2018年5月9日 19:15收件人: ewen0930/PyCharm-Chinese <PyCharm-Chinese@noreply.github.com>抄送: carbont <yupeng08@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[ewen0930/PyCharm-Chinese] 没有找到resources_zh_CN.jar这个包啊？ (#1)@adminlinzi  你好，https://github.com/adminlinzi/mygitworks/blob/master/resources_zhCN.jar  这个打不开了，能否分享一下？谢谢

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ewen0930/PyCharm-Chinese","title":"ewen0930/PyCharm-Chinese","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ewen0930/PyCharm-Chinese"}},"updates":{"snippets":[{"icon":"PERSON","message":"@18810319795 in #1: @adminlinzi  你好，https://github.com/adminlinzi/mygitworks/blob/master/resources_zhCN.jar  这个打不开了，能否分享一下？谢谢"}],"action":{"name":"View Issue","url":"https://github.com/ewen0930/PyCharm-Chinese/issues/1#issuecomment-387705891"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [ewen0930/PyCharm-Chinese] 没有找到resources_zh_CN.jar这个包啊？ (#1)","sections":[{"text":"","activityTitle":"**18810319795**","activityImage":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","activitySubtitle":"@18810319795","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"ewen0930/PyCharm-Chinese\",\"issueId\":1,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"targets":[{"os":"default","uri":"https://github.com/ewen0930/PyCharm-Chinese/issues/1#issuecomment-387705891"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":158438953}"}],"themeColor":"26292E"}

**Comment by sunnnnnnnny** [comment]
是因为下载不到那个jar文件，然后说那个网盘里有，不过网站挂了。老哥，等你有时间了麻烦帮忙发下。




| |
张宇强
邮箱：18829347700@163.com
|

签名由 网易邮箱大师 定制

在2018年05月09日 21:34，carbont 写道：
我记得这文件不用打开，不是压缩包，直接放到pycharm的哪个位置就可以了。不在家，没有电脑用。以上发自我的iPhone------------------ 原始邮件 ------------------发件人: 18810319795 <notifications@github.com>发送时间: 2018年5月9日 19:15收件人: ewen0930/PyCharm-Chinese <PyCharm-Chinese@noreply.github.com>抄送: carbont <yupeng08@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[ewen0930/PyCharm-Chinese] 没有找到resources_zh_CN.jar这个包啊？ (#1)@adminlinzi 你好，https://github.com/adminlinzi/mygitworks/blob/master/resources_zhCN.jar 这个打不开了，能否分享一下？谢谢

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.








{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ewen0930/PyCharm-Chinese","title":"ewen0930/PyCharm-Chinese","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ewen0930/PyCharm-Chinese"}},"updates":{"snippets":[{"icon":"PERSON","message":"@18810319795 in #1: @adminlinzi 你好，https://github.com/adminlinzi/mygitworks/blob/master/resources_zhCN.jar 这个打不开了，能否分享一下？谢谢"}],"action":{"name":"View Issue","url":"https://github.com/ewen0930/PyCharm-Chinese/issues/1#issuecomment-387705891"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [ewen0930/PyCharm-Chinese] 没有找到resources_zh_CN.jar这个包啊？ (#1)","sections":[{"text":"","activityTitle":"**18810319795**","activityImage":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","activitySubtitle":"@18810319795","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"ewen0930/PyCharm-Chinese\",\"issueId\":1,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"targets":[{"os":"default","uri":"https://github.com/ewen0930/PyCharm-Chinese/issues/1#issuecomment-387705891"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":158438953}"}],"themeColor":"26292E"}

**Comment by ewen0930** [comment]
https://github.com/ewen0930/PyCharm-Chinese/releases

Github和百度网盘都能下载，WHY？

**Comment by gaoljhy** [comment]
不行了，都挂不上去了
